function modelName = dz4_build_simulink_model(cfg, modelData)
%DZ4_BUILD_SIMULINK_MODEL Create the reproducible DZ4 State-Space model.

modelName = 'dz4_longitudinal_ss';
rootDir = fileparts(fileparts(mfilename('fullpath')));
modelDir = fullfile(rootDir, 'models');
modelPath = fullfile(modelDir, [modelName '.slx']);

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    load_system(modelPath);
    close_system(modelName, 0);
end

new_system(modelName);
modelWorkspace = get_param(modelName, 'ModelWorkspace');
assignin(modelWorkspace, 'cfg', cfg);
assignin(modelWorkspace, 'A', modelData.A);
assignin(modelWorkspace, 'B', modelData.B);
assignin(modelWorkspace, 'C', modelData.C);
assignin(modelWorkspace, 'D', modelData.D);

set_param(modelName, ...
    'Solver', 'ode45', ...
    'StopTime', 'cfg.stop_time_s', ...
    'RelTol', '1e-9', ...
    'AbsTol', '1e-11', ...
    'MaxStep', '1e-4');

add_block('simulink/Sources/Step', [modelName '/Step delta_1'], ...
    'Position', [30 180 65 210], ...
    'Time', 'cfg.step_time_s', ...
    'Before', '0', ...
    'After', 'cfg.delta_step_rad');
add_block('simulink/Continuous/State-Space', [modelName '/State-Space'], ...
    'Position', [160 145 285 235], ...
    'A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'X0', 'zeros(5,1)');
add_block('simulink/Sinks/To Workspace', [modelName '/States'], ...
    'Position', [360 150 460 180], ...
    'VariableName', 'states', ...
    'SaveFormat', 'Structure With Time');
add_block('simulink/Signal Routing/Demux', [modelName '/Demux'], ...
    'Position', [350 215 355 355], ...
    'Outputs', '5');

scopeNames = {'theta_deg', 'alpha_deg', 'vartheta_deg', ...
    'omega_z_deg_per_s', 'H_m'};
for i = 1:5
    y = 80 + 55*i;
    if i < 5
        gainName = sprintf('To degrees %d', i);
        add_block('simulink/Math Operations/Gain', [modelName '/' gainName], ...
            'Position', [430 y-15 500 y+15], 'Gain', '180/pi');
        add_block('simulink/Sinks/Scope', [modelName '/' scopeNames{i}], ...
            'Position', [560 y-20 600 y+20]);
        add_line(modelName, sprintf('Demux/%d', i), ...
            sprintf('%s/1', gainName), 'autorouting', 'on');
        add_line(modelName, sprintf('%s/1', gainName), ...
            sprintf('%s/1', scopeNames{i}), 'autorouting', 'on');
    else
        add_block('simulink/Sinks/Scope', [modelName '/' scopeNames{i}], ...
            'Position', [560 y-20 600 y+20]);
        add_line(modelName, 'Demux/5', [scopeNames{i} '/1'], ...
            'autorouting', 'on');
    end
end

add_line(modelName, 'Step delta_1/1', 'State-Space/1', 'autorouting', 'on');
add_line(modelName, 'State-Space/1', 'States/1', 'autorouting', 'on');
add_line(modelName, 'State-Space/1', 'Demux/1', 'autorouting', 'on');

save_system(modelName, modelPath);
end
